### ISSUE TITLE
Current undercloud image is broken

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#57]
The current undercloud image (MD5:3074d36e0f6f25a547c27ba0c06281f8.qcow2) is broken.  The `openstack-swift-proxy` service is failing to start:

```
Traceback (most recent call last):
File "/usr/bin/swift-proxy-server", line 23, in <module>
sys.exit(run_wsgi(conf_file, 'proxy-server', **options))
File "/usr/lib/python2.7/site-packages/swift/common/wsgi.py", line 893, in run_wsgi
loadapp(conf_path, global_conf=global_conf)
File "/usr/lib/python2.7/site-packages/swift/common/wsgi.py", line 387, in loadapp
app = ctx.app_context.create()
File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
return self.object_type.invoke(self)
File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
return fix_call(context.object, context.global_conf, **context.local_conf)
File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
val = callable(*args, **kw)
File "/usr/lib/python2.7/site-packages/swift/proxy/server.py", line 570, in app_factory
app = Application(conf)
File "/usr/lib/python2.7/site-packages/swift/proxy/server.py", line 115, in __init__
ring_name='account')
File "/usr/lib/python2.7/site-packages/swift/common/ring/ring.py", line 170, in __init__
self._reload(force=True)
File "/usr/lib/python2.7/site-packages/swift/common/ring/ring.py", line 175, in _reload
ring_data = RingData.load(self.serialized_path)
File "/usr/lib/python2.7/site-packages/swift/common/ring/ring.py", line 87, in load
gz_file = GzipFile(filename, 'rb')
File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/etc/swift/account.ring.gz'
```

**Comment by larsks** [comment]
There are also several selinux AVCs:

```
# grep AVC /var/log/audit/audit.log | wc -l
181
# audit2allow -a


#============= chkpwd_t ==============
allow chkpwd_t unlabeled_t:file { read getattr open };

#============= chronyd_t ==============
allow chronyd_t unlabeled_t:file { read getattr open };

#============= dhcpc_t ==============
allow dhcpc_t unlabeled_t:file { read getattr open execute };
allow dhcpc_t unlabeled_t:lnk_file read;

#============= dnsmasq_t ==============
allow dnsmasq_t unlabeled_t:dir { write add_name };
allow dnsmasq_t unlabeled_t:file { execute read create execute_no_trans write getattr open append };
allow dnsmasq_t unlabeled_t:lnk_file read;

#============= getty_t ==============
allow getty_t unlabeled_t:file { read getattr open };

#============= ifconfig_t ==============
allow ifconfig_t ifconfig_var_run_t:dir mounton;
allow ifconfig_t root_t:dir mounton;
allow ifconfig_t sysfs_t:filesystem getattr;

#============= iptables_t ==============
allow iptables_t unlabeled_t:file { read getattr open };

#============= policykit_t ==============
allow policykit_t unlabeled_t:file { read getattr open };

#============= postfix_master_t ==============
allow postfix_master_t unlabeled_t:file { read getattr open execute };
allow postfix_master_t unlabeled_t:lnk_file read;

#============= postfix_pickup_t ==============
allow postfix_pickup_t unlabeled_t:file { read getattr open execute };
allow postfix_pickup_t unlabeled_t:lnk_file read;

#============= postfix_qmgr_t ==============
allow postfix_qmgr_t unlabeled_t:file { read getattr open execute };
allow postfix_qmgr_t unlabeled_t:lnk_file read;

#============= sendmail_t ==============
allow sendmail_t unlabeled_t:file { read getattr open execute };
allow sendmail_t unlabeled_t:lnk_file read;

#============= ssh_keygen_t ==============
allow ssh_keygen_t unlabeled_t:file { read getattr open execute };
allow ssh_keygen_t unlabeled_t:lnk_file read;

#============= sshd_keygen_t ==============
allow sshd_keygen_t unlabeled_t:file { read getattr open };

#============= sshd_t ==============
allow sshd_t unlabeled_t:file { read getattr open execute };
allow sshd_t unlabeled_t:lnk_file read;

#============= syslogd_t ==============
allow syslogd_t unlabeled_t:file { read getattr open };

#============= system_dbusd_t ==============
allow system_dbusd_t unlabeled_t:file { getattr open };

#============= systemd_hostnamed_t ==============
allow systemd_hostnamed_t unlabeled_t:file { read getattr open };

#============= systemd_logind_t ==============
allow systemd_logind_t unlabeled_t:file { read getattr open };

#============= systemd_sysctl_t ==============
allow systemd_sysctl_t unlabeled_t:file { read getattr open };
```

**Comment by larsks** [comment]
It doesn't look like we're ever calling `virt-customize --selinux-relabel` after modifying files in the undercloud.

**Comment by trown** [comment]
@larsks I am unable to reproduce this issue with the current stable mitaka image (MD5:41b7472778cdd10e53c865c7eab731a1). Are you still seeing it?

As far as SELinux, we are not doing any relabel at the end of the image build. It looks like the ifconfig_t AVC's would be there even with a relabel though.

It would be cool to get SELinux working, but maybe we should separate that out into its own issue.

**Comment by larsks** [comment]
> @larsks I am unable to reproduce this issue with the current stable mitaka image (MD5:41b7472778cdd10e53c865c7eab731a1). Are you still seeing it?

The problem appears to have been resolved by subsequent images.

> As far as SELinux, we are not doing any relabel at the end of the image build. It looks like the ifconfig_t AVC's would be there even with a relabel though.

It looks as if running a relabel reduces the list of exceptions to:

```
allow iptables_t var_run_t:file { read lock open };
```

Since we're running with selinux enabled, we should probably relabel to ensure that we don't get bitten by an unexpected "permission denied" at some point.
